
CREATE TABLE IF NOT EXISTS `#__slideshow_slides` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `catid` int(11) NOT NULL COMMENT 'Category ID',
  `title` varchar(255) NOT NULL COMMENT 'Record title',
  `url` varchar(255) NOT NULL COMMENT 'URL',
  `introtext` mediumtext NOT NULL COMMENT 'Intro',
  `images` text NOT NULL COMMENT 'Images',
  `version` int(11) unsigned NOT NULL COMMENT 'Version',
  `created` datetime NOT NULL COMMENT 'Created time',
  `created_by` int(11) NOT NULL COMMENT 'Author',
  `modified` datetime NOT NULL COMMENT 'Modified time',
  `modified_by` int(11) NOT NULL COMMENT 'Modified user',
  `ordering` int(11) NOT NULL COMMENT 'Ordering key',
  `state` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Record state',
  `publish_up` datetime NOT NULL COMMENT 'Publish start time',
  `publish_down` datetime NOT NULL COMMENT 'Publish end time',
  `checked_out` int(11) NOT NULL COMMENT 'Checkout user',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Checkout time',
  `access` int(11) unsigned NOT NULL COMMENT 'Access viewlevels',
  `language` char(7) NOT NULL COMMENT 'Language key',
  `params` text NOT NULL COMMENT 'Params',
  PRIMARY KEY (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_catid` (`catid`),
  KEY `idx_language` (`language`),
  KEY `idx_checkout` (`checked_out`),
  KEY `cat_index` (`state`,`access`,`catid`),
  KEY `idx_created_by` (`created_by`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
